---


- name: Adding Yaourt (AUR) repository
  copy: src=pacman.conf dest="/etc/pacman.conf" owner=root group=root backup=yes

- name: Updating system packages
  pacman: name=base-devel state=present update_cache=yes
