---


- name: Adding Yaourt (AUR) repository
  lineinfile: dest=/etc/pacman.conf state=present line={{item.line}}
  with_items:
    - { line: '"[archlinuxfr]"' }
    - { line: '"SigLevel = Never"' }
    - { line: '"Server = http://repo.archlinux.fr/$arch"' }

- name: Adding multilib repository (32bit)
  lineinfile: dest=/etc/pacman.conf state=present line={{item.line}}
  with_items:
    - { line: '"[multilib]\nInclude = /etc/pacman.d/mirrorlist"' }

- name: Updating system packages
  pacman: name=base-devel state=present update_cache=yes
