---
#System tasks

- name: Installing I3
  pkgmgr: pkg={{item}} state=present
  with_os_specific:
    - Archlinux: lightdm
    - Archlinux: i3
    - Archlinux: dmenu
    - Archlinux: pcmanfm
    - Archlinux: xarchiver
    - Archlinux: xscreensaver
    - Archlinux: archlinux-xdg-menu

- name: Adding lightdm.conf
  copy: src=lightdm.conf dest="/etc/lightdm/lightdm.conf" backup=yes

- name: Adding .xinitrc
  copy: src=.xinitrc dest="/home/{{username}}/" owner={{username}} group={{username}} backup=yes


