---

# Javascript

- name: Install dependencies
  pkgmgr: pkg={{ item }} update_cache=yes
  with_os_specific:
    - git
    - curl
    - build-essential
    - libssl-dev
  tags: nvm


- name: Checking previous NVM installation
  register: nvm
  stat: "path=/home/{{username}}/.nvm"

- name: Installing Node Version Manager (NVM)
  shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash
  sudo_user: "{{username}}"
  when: nvm.stat.exists == False

- name: Source nvm in ~/.profile
  sudo: yes
  sudo_user: "{{username}}"
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Installing latest NodeJS 0.12.x
  sudo_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && nvm install 0.12
  args:
     executable: /bin/bash

- name: Default latest NodeJS Version
  sudo_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && nvm alias default 0.12
  args:
     executable: /bin/bash

- name: Installing Frontend toolchain
  sudo_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && sudo npm install -g bower yo grunt-cli gulp karma-cli ember-cli coffee-script phantomjs protractor ionic cordova chdir="/home/{{username}}/"
  args:
     executable: /bin/bash

- name: Updating webdriver
  sudo_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && sudo webdriver-manager update
  args:
     executable: /bin/bash
