---

# Development configuration

- name: Installing Version Control Systems
  pkgmgr: pkg={{ item }} state=present
  with_os_specific:
    - git
    - mercurial
    - meld

# Includes development environments
- include: python.yml
- include: ruby.yml
#- include: javascript.yml
#- include: java.yml

- name: Configuring .gitconfig
  template: src=gitconfig.j2 dest="/home/{{username}}/.gitconfig" owner={{username}} group={{username}} mode=0644

- name: Installing terminator
  pkgmgr: pkg=terminator state=present

- name: Installing tmux
  pkgmgr: pkg=tmux state=present

- name: Installing Tmuxinator
  command: gem install tmuxinator
  tags: tmuxinator


- name: Installing Vagrant
  pkgmgr: pkg={{item}} state=present
  with_os_specific:
    - default: vagrant
  tags: vagrant


- name: Installing Chef-DK
  include: ../../../tasks/yaourt-S.yml
  vars:
    packages:
      - "chef-dk"
  tags: vagrant


- name: Installing Vagrant Plugins
  remote_user: "{{username}}"
  command: vagrant plugin install vagrant-vbguest vagrant-share vagrant-libvirt vagrant-lxc 
  command: vagrant plugin install vagrant-omnibus vagrant-chef-zero vagrant-berkshelf
  tags: vagrant
