---

# Docker

- name: Installing docker containers
  pkgmgr: pkg={{item}} state=present
  with_os_specific:
    - Debian: docker.io
      Archlinux: docker

- name: Starting docker daemon on boot
  command: systemctl enable docker
  when: ansible_os_family == 'Archlinux'

- name: Docker on
  service: name=docker state=running

- name: Adding default user to docker group
  user: name={{username}} groups=docker append=yes
