---

# Awesome window manager

- name: Installing Awesome window manager
  pkgmgr: pkg={{item}} state=present
  with_os_specific:
    - Archlinux: awesome
    - Archlinux: gvfs
    - Archlinux: gvfs-afc
    - Archlinux: gvfs-smb
    - Archlinux: gvfs-mtp
    - Archlinux: pcmanfm
    - Archlinux: xarchiver
    - Archlinux: xscreensaver
    - Archlinux: archlinux-xdg-menu
    - Archlinux: lua-filesystem

- name: Adding widgets and plugins
  copy: src={{item}} dest="/home/{{username}}/.config/awesome/" owner={{username}} group={{username}}
  with_items:
    - utils.lua
    - widgets.lua

- name: Adding executable scripts
  copy: src={{item}} dest=/usr/bin/ owner=root group=root mode=0755
  with_items:
    - battery
    - awesome-menu-update
    - lock-suspend

- name: Adding custom Awesome rc.lua
  copy: src=rc.lua dest="/home/{{username}}/.config/awesome/" owner={{username}} group={{username}} backup=yes

- name: Adding .xinitrc
  copy: src=.xinitrc dest="/home/{{username}}/" owner={{username}} group={{username}} backup=yes

- name: Generating Awesome menu
  sudo_user: "{{username}}"
  command: xdg_menu --format awesome --root-menu /etc/xdg/menus/arch-applications.menu > /home/{{username}}/.config/awesome/archmenu.lua
